platform :ios, '9.0'

workspace 'DemoApp.xcworkspace'

target 'DemoApp' do
    use_frameworks!

#     pod 'DCIntrospect-ARC', :inhibit_warnings => true
#     pod 'DZNEmptyDataSet'
#     pod 'SVProgressHUD'
#     pod 'FLEX'
#     pod 'mopub-ios-sdk'
end

target 'DemoAppTests' do
    use_frameworks!

    inherit! :search_paths # Required for not double-linking libraries in the app and test targets.
    pod 'EarlGrey'
end
